#!/usr/bin/env bash
# =========================================
# .FILE
#   nfs-server-conf
#
# .SYNOPSIS
#   Bash script to configure NFS-Linux server
#
# .DESCRIPTION
#   I write this script for
#   `Linux nfs-server 6.8.0-88-generic #89-Ubuntu SMP PREEMPT_DYNAMIC Sat Oct 11 01:02:46 UTC 2025 x86_64 x86_64 GNU/Linux`
#   (ubuntu-24.04.3-live-server-amd64)
#
# .PARAMETER NONE
#   NONE
#
# .INPUTS
#   NONE
#
# .OUTPUTS
#   NONE
#
# .NOTES
#   Version       : 1.0
#   Author        : @ZouariOmar <zouariomar20@gmail.com>
#   Created       : 11/22/2025
#   Change Log    : 9780b36
#
# .EXAMPLE
#   > ./nfs-server-conf
#   --
#   > NET_INTERFACE="enp2s0"       \
#     NET_ADDRESS="172.24.74.2/24" \
#     NET_GW="172.24.74.1"         \
#     NET_DNS_SERVERS="[8.8.8.8]"  \
#     SHARED_DIR='/srv/nfs/share' \
#     NFS_GROUP='zouari_omar'
#     ./nfs_server_conf
# =========================================

#################################
### CUSTOM CONFIGURATION PART ###
#################################
NET_INTERFACE="enp2s0"
NET_SUBNET='X.X.X.X/XX'
NET_ADDRESS="X.X.X.X/XX"
NET_GW="X.X.X.X"
NET_DNS_SERVERS="[X.X.X.X]"
SHARED_DIR='path_to_shared_directory'
NFS_GROUP='group_to_chown_shared_dir'

##################################
### GENERAL CONFIGURATION PART ###
##################################

# Set keymap into fr
sudo sed -i 's/XKBLAYOUT=".*"/XKBLAYOUT="fr"/' /etc/default/keyboard

# Update the system
sudo apt update && sudo apt upgrade

# Change the current hostname
hostnamectl set-hostname nfs-server

##################################
### NETWORK CONFIGURATION PART ###
##################################

# Set the private static ip address
sudo bash -c "cat << 'EOF' > /etc/netplan/01-static.yaml
network:
  version: 2
  renderer: networkd
  ethernets:
    ${NET_INTERFACE}:
      dhcp4: no
      addresses:
        - ${NET_ADDRESS}
      nameservers:
        addresses: ${NET_DNS_SERVERS}
      routes:
        - to: default
          via: ${NET_GW}
EOF"

# Change 01-static.yaml accessibility
sudo chmod 600 /etc/netplan/01-static.yaml

# Apply changes
sudo netplan apply

#####################################
### NFS-SERVER CONFIGURATION PART ###
#####################################

# Install Server NFS-SERVER package
sudo apt install -y nfs-kernel-server nfs-common

# Enable NFS service
sudo systemctl enable --now nfs-server

# Create and Export a Shared Directory
sudo mkdir -p ${SHARED_DIR}

# Add local subnet to the ACL (Access Control List)
echo "${SHARED_DIR} ${NET_SUBNET}(rw,sync,no_subtree_check)" | sudo tee -a /etc/exports

# Apply exports
sudo exportfs -ra

# Give grp permission
sudo chown -R :${NFS_GROUP} ${SHARED_DIR}
sudo chmod -R 775 ${SHARED_DIR}

# Configure Firewall
sudo ufw allow from ${NET_SUBNET} to any port nfs
