#!/usr/bin/env bash
# =========================================
# .FILE
#   qemu_image_setup
#
# .SYNOPSIS
#   [Create|Run|Convert] qemu image
#
# .DESCRIPTION
#   `qemu-cli + linux.iso ==> linux_vm.qcow2`
#   [TESTED] Linux nfs-server 6.8.0-88-generic #89-Ubuntu SMP PREEMPT_DYNAMIC Sat Oct 11 01:02:46 UTC 2025 x86_64 x86_64 GNU/Linux
#   [QEMU-IMAGES] https://drive.google.com/drive/folders/1lB6PC9CFF4Hk3t_BUzBfBoOtKSKMJgSq?usp=drive_link
#
# .PARAMETER NONE
#   NONE
#
# .INPUTS
#   NONE
#
# .OUTPUTS
#   NONE
#
# .NOTES
#   Version       : 1.0
#   Author        : @ZouariOmar <zouariomar20@gmail.com>
#   Created       : 12/07/2025
#   Change Log    : c882d04
#
# .EXAMPLE
#   > ./qemu_image_setup
#   --
#   > ISO_IMAGE='ubuntu-24.04.3-live-server-amd64.iso' \
#     QCOW2_IMAGE='linux_server_vm.qcow2'              \
#     VMDK_IMAGE='linux_server_vm.vmdk'
#     ./qemu_image_setup
# =========================================

#################################
### CUSTOM CONFIGURATION PART ###
#################################
ISO_IMAGE='path_to_iso_file'
QCOW2_IMAGE='path_to_qcow2_file'
VMDK_IMAGE='path_to_vmdk_file'

# Create linux_vm with size 20G
qemu-img create -f qcow2 ${QCOW2_IMAGE} 20G

# Boot QEMU with ISO (only for installation)
qemu-system-x86_64 -m 2G -boot d -cdrom ${ISO_IMAGE} -hda ${QCOW2_IMAGE} -net nic -net user

# Boot QEMU without ISO
# Use -enable-kvm if your CPU supports virtualization
qemu-system-x86_64 -enable-kvm -m 2G -hda ${QCOW2_IMAGE} -net nic -net user

# Convert .qcow2 to .vmdk
qemu-img convert -p -f qcow2 -O vmdk ${QCOW2_IMAGE} ${VMDK_IMAGE}
